export const LABELS={
    headings:{
        websiteName:"userhub",
        login:"Login",
        cancel:"Cancel",
        confirm:"Confirm",
        firstname:"Firstname",
        lastname:"Lastname",
        username:"Username",
        password:"Password",
        confirmPassword:"Confirm Password",
        hasAccount:"Already registered?",
        rememberme:"Remember me",
        email:"Email",
        forgotPassword:"Forgot Password?",
        forgotPasswordMessage:"Enter your email to get reset link.",
        noAccount:"Don't have an account?",
        loginMessage:"Please login to continue",
        register:"Register",
        personaldetails:"Personal Details",
        resetPassword:"Reset Password",
        deactivateAccount:"Deactivate Account",
        oldPassword:"Old Password",
        newPassword:"New password",
        reset:"Reset",
        registerMessage:"Please register to continue",
        setNewPassword:"Set New Password",
        manager:"Manager",
        user:"User",
        admin:"Admin",
        managerusers:"Manage Users",
        active:"Active",
        deactivated:"Deactivated",
        actions:"Actions :",
        activate:"Activate",
        deactivate:"Deactivate",
        edit:"Edit",
        resetLock:"Reset Lock"
    },
    imageUrls:{
        endavaSymbol:"/Endava_Symbol.svg",
        dbImagePath: "http://localhost:8080/images/"
    },
    alterativeTexts:{
        endavaSymbol:"endava-symbol",
        profile:"profile-pic"
    },
    errorMessages:{
        userNameRequired:"Username is required",
        passwordRequired:"Password is required",
        confirmPasswordRequired:"Confirm Password is required",
        passwordsDonotMatch:"Passwords do not match",
        invalidCredentials:"Invalid Credentials",
        emailRequired:"Email is Required",
        invalidEmail:"Invalid Email",
        noAccountFound:"No Account Found",
        fixErrors:"Sorry! From's not happy",
        invalidToken:"Token is invalid or expired.",
        missingToken:"Token is missing.",
        passwordRegexNotFollowed:"Password must be at least 8 characters and contain one uppercase, one lowercase, one digit, and one special character",
        tokenValidationFailed:"Token validation failed. Please try again.",
        passwordSameAsOld:"Cannot be same as old one.",
        somethingWentWrong:"Something went wrong",
        accountLocked:"Account Locked! Try again Tomorrow",
        accountNotActive:"Account Deactivated !",
        firstnameRequired:"Firstname is required",
        lastnameRequired:"Lastname is required",
        passwordMismatch:"Password mismatched.",
        firstnameRegex:"Only letters (A-Z, a-z) allowed",
        lastnameRegex:"Only letters (A-Z, a-z) allowed",
        usernameRegex:"No Spaces Allowed",
        usernameLength:"Should be (4-15) characters",
        emailAlreadyExists:"Email already exist",
        usernameTaken:"Username already taken",
        unsupportedFileType:"Invalid file format. Please upload a JPG or PNG image.",
        profileImageUploadFailed:"Profile image upload fail",
        oldPasswordRequired:"Old Password is required",
        newPasswordRequired:"New Password is required",
        incorrectOldPassword:"Incorrect Old Password",
        passwordInvalid:"Invalid password",
        userIdRequired:"User Id required",
        serverDown:"⚠️ Server Down",
        loginRequired:"Login required",
        unauthorized:"🔒Unauthorized Access ",
        unauthorizedMsg:"You do not have permission to access this page."
    },
    successMessages:{
        newPasswordSet:" New Password set successfully!",
        passwordreset:"Password reset successfully!",
        userDeactivated:"User deactivated successfully!",
        login:"Logged in successfully!",
        logout:"Logged out successfully!",
        register:"Registered successfully ! \n Login to Continue.",
        userActivated:"User activated successfully!",
        userLockReset:"Lock reset successfully!"
    },
    type:{
        success:"success",
        warning:"warning",
        error:"error",
        info:"info",
        question:"question"
    },
    general:{
        user:"user",
        encodingType:"aes",
        passwordResetMsg:"Paste this link in your browser to set new password \n"
    },
    roles:{
        manger:"ROLE_MANAGER",
        user:"ROLE_USER",
        admin:"ROLE_ADMIN"
    },
    confirmation:{
        deactivateUser:"Are you sure you want to deactivate this user?",
        activateUser:"Are you sure you want to activate this user?",
        resetLock:"Are you sure you want to reset lock for this user?"
    }
}